name: OWASP Dependency-Check

on:
  push:
    branches: 
        - main
    tags:
       - 'v*'
  pull_request:
    types: [opened, synchronize, reopened]
    branches: 
        - main

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "MiProyecto"
          format: "HTML"
          out: "dependency-check-report"

      - name: Upload report artifact
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report
